apiVersion: v1
kind: Secret
metadata:
  name: flex-bot-secrets
  namespace: flex-production
type: Opaque
stringData:
  DATABASE_URL: "postgresql://user:password@postgres-service:5432/flexbot"
  REDIS_URL: "redis://:redis-password@redis-service:6379/0"
  REDIS_PASSWORD: "redis-password"
  SECRET_KEY: "your-super-secret-key-here-change-in-production"
  ENCRYPTION_KEY: "your-encryption-key-here-change-in-production"
---
apiVersion: v1
kind: Secret
metadata:
  name: proxy-secrets
  namespace: flex-production
type: Opaque
stringData:
  LUMINATI_USERNAME: "your-luminati-username"
  LUMINATI_PASSWORD: "your-luminati-password"
  OXYLABS_API_KEY: "your-oxylabs-api-key"
  SMARTPROXY_TOKEN: "your-smartproxy-token"